export async function POST(req: Request) {
  try {
    const { description } = await req.json();

    if (!description || description.trim().length === 0) {
      return Response.json(
        { error: 'Description is required' },
        { status: 400 }
      );
    }

    const apiKey = process.env.OPENROUTER_API_KEY ?? process.env.NEXT_PUBLIC_OPENROUTER_API_KEY;

    if (!process.env.OPENROUTER_API_KEY && process.env.NEXT_PUBLIC_OPENROUTER_API_KEY) {
      console.warn('Using NEXT_PUBLIC_OPENROUTER_API_KEY as fallback. Migrate to OPENROUTER_API_KEY.');
    }

    if (!apiKey) {
      console.error('OPENROUTER_API_KEY not configured');
      return Response.json(
        { error: 'API not configured' },
        { status: 500 }
      );
    }

    const response = await fetch(
      'https://openrouter.ai/api/v1/chat/completions',
      {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json',
          'HTTP-Referer': 'https://invoice-flow.vercel.app',
        },
        body: JSON.stringify({
          model: 'openai/gpt-oss-120b:free',
          messages: [
            {
              role: 'user',
              content: `Expande y profesionaliza en 1-2 líneas esta descripción de servicio/producto para una factura:
"${description}"

Responde SOLO con el texto expandido, sin comillas ni explicaciones.`,
            },
          ],
          reasoning: {
            enabled: true,
          },
          temperature: 0.7,
          max_tokens: 150,
        }),
      }
    );

    // Manejo específico de rate limit
    if (response.status === 429) {
      console.warn('OpenRouter API rate limit exceeded (429)');
      return Response.json(
        { error: 'Rate limit exceeded. Try again later.' },
        { status: 429 }
      );
    }

    // Manejo de otros errores HTTP
    if (!response.ok) {
      const errorData = await response.text();
      console.error(`OpenRouter API error (${response.status}):`, errorData);

      if (response.status === 400) {
        return Response.json(
          { error: 'Invalid request to API' },
          { status: 400 }
        );
      }

      if (response.status === 401 || response.status === 403) {
        return Response.json(
          { error: 'API key invalid or expired' },
          { status: 401 }
        );
      }

      if (response.status === 500 || response.status === 502 || response.status === 503) {
        return Response.json(
          { error: 'API service temporarily unavailable' },
          { status: 503 }
        );
      }

      return Response.json(
        { error: `API error: ${response.statusText}` },
        { status: response.status }
      );
    }

    const data = await response.json();
    
    // Validar respuesta de OpenRouter
    if (!data.choices || !data.choices[0] || !data.choices[0].message) {
      console.error('Invalid response from OpenRouter API:', data);
      return Response.json(
        { error: 'Empty response from AI' },
        { status: 500 }
      );
    }

    const expandedText = data.choices[0].message.content || description;
    
    if (!expandedText || expandedText.trim().length === 0) {
      console.error('No text in OpenRouter response');
      return Response.json(
        { error: 'No text generated by AI' },
        { status: 500 }
      );
    }

    return Response.json({ expandedDescription: expandedText.trim() });
  } catch (error) {
    console.error('Error in expand-description:', error);
    
    // Detectar errores de red/conexión
    if (error instanceof TypeError) {
      return Response.json(
        { error: 'Network error. Check your connection.' },
        { status: 503 }
      );
    }

    return Response.json(
      { error: 'Failed to expand description' },
      { status: 500 }
    );
  }
}
